<h3>Vectors - Numeric, Character, Logical</h3>

In [58]:
#Numeric
c(1995,1999,2010,2002)

#Character
c("Toy Story", "Akira", "The Artist")

#Logical
1997 > 2002 #false

[1] 1995 1999 2010 2002

[1] "Toy Story"  "Akira"      "The Artist"

[1] FALSE

In [59]:
movie_ratings <- c(7.3,8.5,6.9,8.2,8.0,9.3,7.5)
movie_ratings > 7.5 #checks every element in vector

[1] FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE

<h3>Factors (variables that can take on limited number of values)
        eg. categorical variables (vs continuous variables: infinite no. of values)</h3>

In [60]:
genre_vector <- c("Comedy", "Comedy", "Animation", "Crime")
genre_factor <- factor(genre_vector)
genre_factor

#Summarizing factors
summary(genre_vector) #basic info abt structure and content
summary(genre_factor) #no. of occurrences of each component categories

[1] Comedy    Comedy    Animation Crime    
Levels: Animation Comedy Crime

   Length     Class      Mode 
        4 character character 

Animation    Comedy     Crime 
        1         2         1

<h3>Types of factors</h3>

1. Nominal categorical variables have no implied order
2. Ordinal variables have ordering

In [61]:
#Ordered factors
movielength_vector <- c("Very short", "Short", "Medium", "Short",
                        "Long", "Very Short", "Very Long")
movielength_vector

[1] "Very short" "Short"      "Medium"     "Short"      "Long"      
[6] "Very Short" "Very Long"

In [62]:
movielength_factor <- factor(movielength_vector)
movielength_factor
movielength_orderedfactor <- factor(movielength_vector,
                                    ordered = TRUE,
                                    levels = c("Very Short", "Short", "Medium",
                                                "Long", "Very Long"))
movielength_orderedfactor

[1] Very short Short      Medium     Short      Long       Very Short Very Long 
Levels: Long Medium Short Very Long Very Short Very short

[1] <NA>       Short      Medium     Short      Long       Very Short Very Long 
Levels: Very Short < Short < Medium < Long < Very Long

<h3>Vector Operations</h3>

1. Name the elements of vector
2. Return the length of vector
3. Sort vector
4. Find smallest or largest number in vector
5. Return ave of numbers in vector
6. Return vector summary
7. Index values in vector
8. Identitfy missigng values in vector
9. Perform arithmetic on values in vector

In [63]:
#names() function
year <- c(1985, 1999, 2010, 2002)
names(year) <- c("The Breakfast Club", "American Beauty",
                "Black Swan", "Chicago") #maps year and title together
year['Black Swan']

Black Swan 
      2010

In [64]:
#length() function
length(year)

[1] 4

In [65]:
#sort() function
sort(year)

The Breakfast Club    American Beauty            Chicago         Black Swan 
              1985               1999               2002               2010

In [66]:
#min() max() function
min(year)
max(year)

[1] 1985

[1] 2010

In [67]:
#mean() function
cost_2014 <- c(8.6, 8.5, 8.1)
mean(cost_2014)
#or
sum(cost_2014)/length(cost_2014)

[1] 8.4

[1] 8.4

In [68]:
#summary() function
summary(cost_2014)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   8.10    8.30    8.50    8.40    8.55    8.60 

In [69]:
#vector index function
cost_2014[2] #2nd element
#or vector in []
cost_2014[c(1,3)] #individual elements
cost_2014[1:3] #range of elements to display

#return -ve index values
titles <- c("Black Swan", "Casino", "City of God", "Jumanji", "Toy Story")
titles[-3] #removes element in index 3

#out of range
cost_2014[100] #shows NA

#conditional index
cost_2014 > 8.2

[1] 8.5

[1] 8.6 8.1

[1] 8.6 8.5 8.1

[1] "Black Swan" "Casino"     "Jumanji"    "Toy Story"

[1] NA

[1]  TRUE  TRUE FALSE

In [70]:
#arithmetic done element wise

age <- c(14,16,12,10,18,18)
number <- c(2,3,0,2,6,3)
multiply <- age*number
multiply

cost_2014 <- c(8.6, 8.5, 8.1)
cost_2014*10

[1]  28  48   0  20 108  54

[1] 86 85 81

<h3>Lists</h3>

In [71]:
movie <- list("Toy Story", 1995, c("Animation", "Adventure", "Comedy"))
movie
movie[3]

[[1]]
[1] "Toy Story"

[[2]]
[1] 1995

[[3]]
[1] "Animation" "Adventure" "Comedy"

[[1]]
[1] "Animation" "Adventure" "Comedy"

In [72]:
#Named Lists
movie <- list(name="Toy Story",
              year=1995,
              genre=c("Animation", "Adventure", "Comedy"))
movie

$name
[1] "Toy Story"

$year
[1] 1995

$genre
[1] "Animation" "Adventure" "Comedy"

In [75]:
movie$genre
#or
movie["genre"]

print("Append new element:")
movie2=movie

#appending new element to end of list
movie2["age"] <- 22
movie2

[1] "Animation" "Adventure" "Comedy"

$genre
[1] "Animation" "Adventure" "Comedy"

[1] "Append new element:"


$name
[1] "Toy Story"

$year
[1] 1995

$genre
[1] "Animation" "Adventure" "Comedy"   

$age
[1] 22

<h3>Arrays and Matrices</h3>

In [85]:
#Arrays
movie_vector <- c("Akira", "Toy Story", "Room", "The Wave", "Whiplash",
                  "Star Wars", "The Ring", "The Artist", "Jumanji")
movie_array <- array(movie_vector, dim=c(4,3))
movie_array

movie_array[3,2]
movie_array[1,]

[,1]      [,2]       [,3]     
[1,] Akira     Whiplash   Jumanji  
[2,] Toy Story Star Wars  Akira    
[3,] Room      The Ring   Toy Story
[4,] The Wave  The Artist Room

[1] "The Ring"

[1] "Akira"    "Whiplash" "Jumanji"

In [88]:
#Matrices
movie_vector <- c("Akira", "Toy Story", "Room", "The Wave", "Whiplash",
                  "Star Wars", "The Ring", "The Artist", "Jumanji")

###        By default, matrix is arranged by columns!         ###

movie_matrix <- matrix(movie_vector, nrow=3, ncol=3)
movie_matrix2 <- matrix(movie_vector, nrow=3, ncol=3, byrow=TRUE)
movie_matrix
movie_matrix2

movie_matrix[3,2]
movie_matrix[2,]

[,1]      [,2]      [,3]      
[1,] Akira     The Wave  The Ring  
[2,] Toy Story Whiplash  The Artist
[3,] Room      Star Wars Jumanji

[,1]     [,2]       [,3]     
[1,] Akira    Toy Story  Room     
[2,] The Wave Whiplash   Star Wars
[3,] The Ring The Artist Jumanji

[1] "Star Wars"

[1] "Toy Story"  "Whiplash"   "The Artist"